-- liquibase formatted sql
-- changeset denny:create table ads

create table ads(
 id integer generated by default as identity primary key,
 title varchar,
 price integer,
 description varchar,
 image_id integer references image(id),
 users_id integer references users(id)
 );