-- liquibase formatted sql
-- changeset denny:create tables

 CREATE TABLE IF NOT EXISTS public.ads
 (
     id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
     description character varying(255) COLLATE pg_catalog."default",
     price integer,
     title character varying(255) COLLATE pg_catalog."default",
     image_id integer,
     users_id integer,
     CONSTRAINT ads_pkey PRIMARY KEY (id),
     CONSTRAINT fk5ulsb592o2ufgiilb0827qrrt FOREIGN KEY (image_id)
         REFERENCES public.image (id) MATCH SIMPLE
         ON UPDATE NO ACTION
         ON DELETE NO ACTION,
     CONSTRAINT fka9v7u2650v34fao0dlo02dfuw FOREIGN KEY (users_id)
         REFERENCES public.users (id) MATCH SIMPLE
         ON UPDATE NO ACTION
         ON DELETE NO ACTION
 )

 TABLESPACE pg_default;

 ALTER TABLE IF EXISTS public.ads
     OWNER to "Denny";



CREATE TABLE IF NOT EXISTS public.comments
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    create_at timestamp without time zone,
    text character varying(255) COLLATE pg_catalog."default",
    ads_id integer,
    users_id integer,
    CONSTRAINT comments_pkey PRIMARY KEY (id),
    CONSTRAINT fkjxtjsac088tc5ixecvuhe3ujg FOREIGN KEY (ads_id)
        REFERENCES public.ads (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkt55y2infwbbw3o942o2mhm0v4 FOREIGN KEY (users_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.comments
    OWNER to "Denny";



CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default",
    first_name character varying(255) COLLATE pg_catalog."default",
    last_name character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    phone character varying(255) COLLATE pg_catalog."default",
    role character varying(255) COLLATE pg_catalog."default",
    image_id integer,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT fklqj25c28swu46s4jbudd7hore FOREIGN KEY (image_id)
        REFERENCES public.image (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to "Denny";



CREATE TABLE IF NOT EXISTS public.image
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    data bytea,
    size bigint,
    media_type character varying(255) COLLATE pg_catalog."default",
    ads_id integer,
    users_id integer,
    CONSTRAINT image_pkey PRIMARY KEY (id),
    CONSTRAINT fk963xks7b6tfiqnm2cgwg1xyew FOREIGN KEY (ads_id)
        REFERENCES public.ads (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkggebt17dxlau3uo9ky02o8vum FOREIGN KEY (users_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.image
    OWNER to "Denny";
